Repository nettee-space/frontend-sample-monorepo-simple-crud, pull requests merged in 2025-02, with the labels that each got.

#6 Update issue templates
  .github/ISSUE_TEMPLATE/기능-요청-템플릿-.md
  .github/ISSUE_TEMPLATE/버그-이슈-템플릿.md
Labels: type: documentation, status: in-progress

#10 PR Template 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: documentation, status: in-progress

#12 프로젝트 초기 세팅 eslint, husky, lint-staged 적용
  .eslintrc.js
  .husky/pre-commit
  apps/web/app/layout.tsx
  apps/web/app/page.tsx
  apps/web/components/providers.tsx
  apps/web/components/stykle.css
  apps/web/eslint.config.js
  apps/web/package.json
  apps/web/tailwind.config.ts
  eslint.config.js
  package.json
  packages/eslint-config/base.js
  packages/eslint-config/next.js
  packages/eslint-config/package.json
  packages/eslint-config/react-internal.js
  packages/ui/eslint.config.js
  packages/ui/postcss.config.mjs
  packages/ui/src/components/button.tsx
  packages/ui/src/lib/utils.ts
  packages/ui/tailwind.config.ts
  pnpm-lock.yaml
  prettier.config.js
Labels: type: chore, status: in-progress

#14 게시판 API 구현 및 Swagger 문서화
  .gitignore
  apps/server/README.md
  apps/server/eslint.config.js
  apps/server/next-env.d.ts
  apps/server/next.config.ts
  apps/server/package.json
  apps/server/src/app/api/posts/[id]/comments/[commentId]/replies/[replyId]/route.ts
  apps/server/src/app/api/posts/[id]/comments/[commentId]/replies/route.ts
  apps/server/src/app/api/posts/[id]/comments/[commentId]/route.ts
  apps/server/src/app/api/posts/[id]/comments/route.ts
  apps/server/src/app/api/posts/[id]/route.ts
  apps/server/src/app/api/posts/infinite/route.ts
  apps/server/src/app/api/posts/paginated/route.ts
  apps/server/src/app/api/posts/route.ts
  apps/server/src/app/layout.tsx
  apps/server/src/app/page.tsx
  apps/server/src/components/react-swagger.tsx
  apps/server/src/lib/swagger.ts
  apps/server/src/types/index.ts
  apps/server/src/utils/index.ts
  apps/server/tsconfig.json
  pnpm-lock.yaml
Labels: type: feature, status: in-progress

#26 워크스페이스 패키지를 위한 tsup 기반 빌드 시스템 구현
  packages/build-config/README.md
  packages/build-config/index.js
  packages/build-config/package.json
  pnpm-lock.yaml
  turbo.json
Labels: type: feature, status: in-progress

#30 터보레포 Custom generators 구현(일반/React 패키지)
  .prettierignore
  README.md
  package.json
  pnpm-lock.yaml
  turbo/generators/config.ts
  turbo/generators/package.json
  turbo/generators/templates/build.js.hbs
  turbo/generators/templates/eslint.config.js.hbs
  turbo/generators/templates/package.json.hbs
  turbo/generators/templates/react/eslint.config.js.hbs
  turbo/generators/templates/react/package.json.hbs
  turbo/generators/templates/react/tsconfig.json.hbs
  turbo/generators/templates/src/index.ts.hbs
  turbo/generators/templates/tsconfig.json.hbs
Labels: type: chore, status: in-progress
